# Generated by Django 4.1.2 on 2022-10-22 18:03

import classlist.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('catalog_number', models.CharField(max_length=4)),
                ('semester_code', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('units', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_abbr', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, max_length=10)),
                ('start_time', models.CharField(blank=True, max_length=100)),
                ('end_time', models.CharField(blank=True, max_length=100)),
                ('facility_description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_dept', models.CharField(blank=True, max_length=4)),
                ('course_num', models.IntegerField(default=0)),
                ('section_id', models.IntegerField(default=0)),
                ('section_number', models.CharField(blank=True, max_length=4)),
                ('component', models.CharField(blank=True, max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('wait_list', models.IntegerField(default=0)),
                ('wait_cap', models.IntegerField(default=0)),
                ('enrollment_total', models.IntegerField(default=0)),
                ('enrollment_available', models.IntegerField(default=0)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classlist.course')),
                ('instructor', models.ForeignKey(default=classlist.models.Instructor.get_default_instructor, on_delete=django.db.models.deletion.CASCADE, to='classlist.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=classlist.models.Department.get_default_dept, on_delete=django.db.models.deletion.CASCADE, to='classlist.department'),
        ),
    ]
