# Generated by Django 4.1.1 on 2022-11-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(choices=[(1, 'First year'), (2, 'Second year'), (3, 'Third year'), (4, 'Fourth year'), (5, 'Other')], default=5),
        ),
    ]
