# Generated by Django 4.1.2 on 2022-10-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='associated_course',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='classlist.section'),
        ),
    ]
