# Generated by Django 4.1.1 on 2022-11-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='days',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
