# Generated by Django 4.1.2 on 2022-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('Credits', models.IntegerField()),
            ],
        ),
    ]
