# Generated by Django 4.1.2 on 2022-11-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=200)),
                ('mon', models.BooleanField(blank=True)),
                ('tue', models.BooleanField(blank=True)),
                ('wed', models.BooleanField(blank=True)),
                ('thu', models.BooleanField(blank=True)),
                ('fri', models.BooleanField(blank=True)),
                ('sat', models.BooleanField(blank=True)),
                ('sun', models.BooleanField(blank=True)),
            ],
        ),
    ]
