# Generated by Django 4.1.2 on 2022-10-22 19:38

import classlist.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=classlist.models.Department.get_default_dept, on_delete=django.db.models.deletion.CASCADE, to='classlist.department'),
        ),
    ]
