# Generated by Django 4.1.1 on 2022-11-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0002_account_account_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='USERNAME_FIELD',
        ),
    ]
