# Generated by Django 4.1.2 on 2022-10-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0002_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Class_title',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Credits',
        ),
        migrations.AddField(
            model_name='class',
            name='catalog_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='class_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='component',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='course_section',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='enrollment_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='enrollment_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='semester_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='wait_cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='wait_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
