# Generated by Django 4.1.2 on 2022-11-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0002_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='class_name',
            new_name='course_name',
        ),
    ]
