# Generated by Django 4.1.1 on 2022-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0002_alter_meetings_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='catalog_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_abbr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='component',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='course_dept',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='course_num',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
