# Generated by Django 4.1.1 on 2022-10-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0002_alter_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
