# Generated by Django 4.2.dev20220917173820 on 2022-11-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0002_department_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="last_updated",
        ),
        migrations.AlterField(
            model_name="account",
            name="year",
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="section",
            name="course_num",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
