# Generated by Django 4.1.3 on 2022-11-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.URLField(default='/static/classlist/default_account_image.png'),
        ),
    ]
