# Generated by Django 4.1.2 on 2022-10-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0002_meetings_associated_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='associated_course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='classlist.section'),
        ),
    ]
