# Generated by Django 4.1.1 on 2022-11-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0003_alter_course_catalog_number_alter_course_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
