# Generated by Django 4.2.dev20220917173820 on 2022-11-10 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classlist",
            "0003_remove_department_last_updated_alter_account_year_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 10, 17, 44, 26, 528216, tzinfo=datetime.timezone.utc
                ),
                verbose_name="last updated",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="year",
            field=models.IntegerField(
                choices=[
                    (1, "First year"),
                    (2, "Second year"),
                    (3, "Third year"),
                    (4, "Fourth year"),
                    (5, "Other"),
                ],
                default=5,
            ),
        ),
    ]
