# Generated by Django 4.1.2 on 2022-11-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0003_rename_class_name_schedule_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fri',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mon',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sat',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sun',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thu',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tue',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wed',
            field=models.BooleanField(),
        ),
    ]
