# Generated by Django 4.1.2 on 2022-10-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0003_alter_meetings_associated_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='associated_course',
            new_name='section',
        ),
    ]
