# Generated by Django 4.1.1 on 2022-10-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0003_user_is_anonymous_user_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='classlist.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='classlist.section'),
        ),
        migrations.CreateModel(
            name='Friend_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='classlist.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='classlist.user')),
            ],
        ),
    ]
