# Generated by Django 4.1.2 on 2022-10-16 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0003_remove_class_class_title_remove_class_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 17, 47, 2, 621242, tzinfo=datetime.timezone.utc), verbose_name='date updated'),
        ),
    ]
