# Generated by Django 4.1.2 on 2022-10-16 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0004_class_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
    ]
