# Generated by Django 4.1.1 on 2022-11-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0004_user_friends_user_schedule_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='received_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='to_user', to='classlist.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='sent_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='from_user', to='classlist.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='my_friends', to='classlist.user'),
        ),
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
