# Generated by Django 4.1.3 on 2022-11-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0004_rename_account_comment_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='schedule',
        ),
    ]
