# Generated by Django 4.2.dev20220917173820 on 2022-11-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0005_account_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="profile_picture",
        ),
    ]
