# Generated by Django 4.2.dev20220917173820 on 2022-10-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0005_alter_class_last_updated"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Class",
            new_name="Course",
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_abbr", models.CharField(max_length=4)),
                (
                    "dept_classes",
                    models.ManyToManyField(blank=True, to="classlist.course"),
                ),
            ],
        ),
    ]
