# Generated by Django 4.1.1 on 2022-11-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0005_user_received_friend_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
