# Generated by Django 4.2.dev20220917173820 on 2022-10-19 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0006_rename_class_course_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="dept_classes",
            new_name="dept_courses",
        ),
    ]
