# Generated by Django 4.2.dev20220917173820 on 2022-11-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0006_remove_account_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Friend_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_user", models.IntegerField(default=0)),
                ("to_user", models.IntegerField(default=0)),
            ],
        ),
    ]
