# Generated by Django 4.2.dev20220917173820 on 2022-10-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0007_rename_dept_classes_department_dept_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="dept_courses",
            field=models.ManyToManyField(to="classlist.course"),
        ),
    ]
