# Generated by Django 4.2.dev20220917173820 on 2022-11-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0007_friend_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="received_friend_requests",
        ),
        migrations.RemoveField(
            model_name="account",
            name="sent_friend_requests",
        ),
        migrations.AlterField(
            model_name="friend_request",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_user",
                to="classlist.account",
            ),
        ),
        migrations.AlterField(
            model_name="friend_request",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_user",
                to="classlist.account",
            ),
        ),
    ]
