# Generated by Django 4.2.dev20220917173820 on 2022-10-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0008_alter_department_dept_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="dept_courses",
        ),
    ]
