# Generated by Django 4.2.dev20220917173820 on 2022-10-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "classlist",
            "0010_course_facility_description_course_instructor_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="facility_description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="intructor_email",
        ),
        migrations.RemoveField(
            model_name="course",
            name="meeting_days",
        ),
    ]
