# Generated by Django 4.2.dev20220917173820 on 2022-10-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0011_remove_course_facility_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="units",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
