# Generated by Django 4.2.dev20221019003145 on 2022-10-20 05:05

import classlist.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0013_instructor_meeting_remove_course_instructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=classlist.models.Instructor.get_default_instructor, on_delete=django.db.models.deletion.CASCADE, to='classlist.instructor'),
        ),
    ]
