# Generated by Django 4.2.dev20220917173820 on 2022-10-20 19:04

import classlist.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0014_course_instructor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meetings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.CharField(blank=True, max_length=10)),
                ("start_time", models.CharField(blank=True, max_length=100)),
                ("end_time", models.CharField(blank=True, max_length=100)),
                ("facility_description", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField(default=0)),
                ("section_number", models.IntegerField(default=0)),
                ("component", models.CharField(blank=True, max_length=20)),
                ("capacity", models.IntegerField(default=0)),
                ("wait_list", models.IntegerField(default=0)),
                ("wait_cap", models.IntegerField(default=0)),
                ("enrollment_total", models.IntegerField(default=0)),
                ("enrollment_available", models.IntegerField(default=0)),
                ("topic", models.CharField(blank=True, max_length=200)),
                (
                    "instructor",
                    models.ForeignKey(
                        default=classlist.models.Instructor.get_default_instructor,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classlist.instructor",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Meeting",
        ),
        migrations.RemoveField(
            model_name="course",
            name="catalog_number",
        ),
        migrations.RemoveField(
            model_name="course",
            name="class_capacity",
        ),
        migrations.RemoveField(
            model_name="course",
            name="component",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_number",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_section",
        ),
        migrations.RemoveField(
            model_name="course",
            name="enrollment_available",
        ),
        migrations.RemoveField(
            model_name="course",
            name="enrollment_total",
        ),
        migrations.RemoveField(
            model_name="course",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="course",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="course",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="course",
            name="wait_cap",
        ),
        migrations.RemoveField(
            model_name="course",
            name="wait_list",
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                default=classlist.models.Department.get_default_dept,
                on_delete=django.db.models.deletion.CASCADE,
                to="classlist.department",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
