# Generated by Django 4.2.dev20220917173820 on 2022-10-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0015_meetings_section_delete_meeting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
