# Generated by Django 4.2.dev20220917173820 on 2022-10-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classlist", "0016_course_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="section_number",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
