# Generated by Django 4.1.2 on 2022-10-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0017_alter_section_section_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catalog_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
