# Generated by Django 4.1.2 on 2022-10-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0018_course_catalog_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='catalog_number',
            field=models.CharField(max_length=4),
        ),
    ]
